In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

In [2]:
#read in csv file, utitilizing read.csv method
results_df = pd.read_csv("results.csv")
results_df.dropna(axis=1)
results_df

,Overall,2019,2018,2017,2016,2015
0,Overall,2019.000000,2018.000000,2017.000000,2016.000000,2015.000000
1,0.879545455,0.898876,0.886364,0.920455,0.852273,0.909091
2,0.886363636,0.842697,0.818182,0.897727,0.863636,0.875000
3,0.859090909,0.898876,0.886364,0.909091,0.818182,0.943182
4,0.863636364,0.898876,0.875000,0.863636,0.875000,0.863636
5,0.822727273,0.786517,0.818182,0.795455,0.818182,0.818182
6,0.825,0.853933,0.818182,0.784091,0.829545,0.772727
7,0.809090909,0.786517,0.818182,0.784091,0.795455,0.795455
8,0.815909091,0.786517,0.784091,0.784091,0.784091,0.784091
9,0.822727273,0.786517,0.784091,0.784091,0.784091,0.784091
10,0.815909091,0.786517,0.784091,0.784091,0.784091,0.784091
11,0.815909091,0.786517,0.784091,0.784091,0.784091,0.784091
12,0.815909091,0.786517,0.784091,0.784091,0.784091,0.784091
13,0.813636364,0.797753,0.772727,0.795455,0.784091,0.806818
14,0.827272727,0.876404,0.840909,0.772727,0.795455,0.829545
15,0.811363636,0.764045,0.750000,0.806818,0.795455,0.772727
16,0.809090909,0.797753,0.795455,0.795455,0.784091,0.761364
17,0.815909091,0.786517,0.784091,0.784091,0.784091,0.784091
18,0.884090909,0.921348,0.784091,0.954545,0.909091,0.954545

In [3]:
new_results_df= results_df.drop(columns=['Unnamed: 7'])
new_results_df

KeyError: "['Unnamed: 7'] not found in axis"

In [ ]:
indexed_df = new_results_df.set_index('Unnamed: 0')
indexed_df

In [ ]:
indexed_df.columns = ['Overall','2019', '2018', '2017', '2016', '2015']
indexed_df.head()

In [ ]:
indexed_df.to_csv('results2.csv', index=False)