In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

In [2]:
#read in csv file, utitilizing read.csv method
results_df = pd.read_csv("results.csv")
results_df

   Unnamed: 0   Overall      2019      2018      2017      2016      2015
0           W  0.879545  0.898876  0.886364  0.920455  0.852273  0.909091
1     BARTHAG  0.886364  0.842697  0.818182  0.897727  0.863636  0.875000
2       ADJOE  0.859091  0.898876  0.886364  0.909091  0.818182  0.943182
3       ADJDE  0.863636  0.898876  0.875000  0.863636  0.875000  0.863636
4       EFG_O  0.822727  0.786517  0.818182  0.795455  0.818182  0.818182
5       EFG_D  0.825000  0.853933  0.818182  0.784091  0.829545  0.772727
6         TOR  0.809091  0.786517  0.818182  0.784091  0.795455  0.795455
7        TORD  0.815909  0.786517  0.784091  0.784091  0.784091  0.784091
8         ORB  0.822727  0.786517  0.784091  0.784091  0.784091  0.784091
9         DRB  0.815909  0.786517  0.784091  0.784091  0.784091  0.784091
10        FTR  0.815909  0.786517  0.784091  0.784091  0.784091  0.784091
11       FTRD  0.815909  0.786517  0.784091  0.784091  0.784091  0.784091
12       2P_O  0.813636  0.797753  0.772727  0.795455  0.784091  0.806818
13       2P_D  0.827273  0.876404  0.840909  0.772727  0.795455  0.829545
14       3P_O  0.811364  0.764045  0.750000  0.806818  0.795455  0.772727
15       3P_D  0.809091  0.797753  0.795455  0.795455  0.784091  0.761364
16      ADJ_T  0.815909  0.786517  0.784091  0.784091  0.784091  0.784091
17        WAB  0.884091  0.921348  0.784091  0.954545  0.909091  0.954545

In [4]:
indexed_df = results_df.set_index('Unnamed: 0')
indexed_df

             Overall      2019      2018      2017      2016      2015
Unnamed: 0
W           0.879545  0.898876  0.886364  0.920455  0.852273  0.909091
BARTHAG     0.886364  0.842697  0.818182  0.897727  0.863636  0.875000
ADJOE       0.859091  0.898876  0.886364  0.909091  0.818182  0.943182
ADJDE       0.863636  0.898876  0.875000  0.863636  0.875000  0.863636
EFG_O       0.822727  0.786517  0.818182  0.795455  0.818182  0.818182
EFG_D       0.825000  0.853933  0.818182  0.784091  0.829545  0.772727
TOR         0.809091  0.786517  0.818182  0.784091  0.795455  0.795455
TORD        0.815909  0.786517  0.784091  0.784091  0.784091  0.784091
ORB         0.822727  0.786517  0.784091  0.784091  0.784091  0.784091
DRB         0.815909  0.786517  0.784091  0.784091  0.784091  0.784091
FTR         0.815909  0.786517  0.784091  0.784091  0.784091  0.784091
FTRD        0.815909  0.786517  0.784091  0.784091  0.784091  0.784091
2P_O        0.813636  0.797753  0.772727  0.795455  0.784091  0.806818
2P_D        0.827273  0.876404  0.840909  0.772727  0.795455  0.829545
3P_O        0.811364  0.764045  0.750000  0.806818  0.795455  0.772727
3P_D        0.809091  0.797753  0.795455  0.795455  0.784091  0.761364
ADJ_T       0.815909  0.786517  0.784091  0.784091  0.784091  0.784091
WAB         0.884091  0.921348  0.784091  0.954545  0.909091  0.954545

In [5]:
indexed_df.to_csv('results2.csv')